<!DOCTYPE html>
<html>
<head>
  <title>Speedport Entry 2i</title>
  <style>
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
      background-color: LIGHTBLUE; /* Set the desired background color */
      font-family: Arial, sans-serif;
    }

    .container {
      max-width: 4000px;
      padding: 30px;
      background-color: rgba(255, 255, 255, 0.8);
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .ui-text {
      background-color: LIGHTBLUE;
      color: #000000;
      padding: 10px;
      border-radius: 5px;
      font-size: 20px;
      margin-bottom: 20px;
    }

    .container label,
    .container input,
    .container input[type="submit"] {
      width: 100%;
      margin-bottom: 10px;
      padding: 8px;
      font-size: 16px;
      border-radius: 3px;
      border: 1px solid #ccc;
    }

    .container input[type="submit"] {
      background-color: #00fff8;
      color: #fff;
      cursor: pointer;
    }

    .container input[type="submit"]:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="ui-text">
      Welcome to Speedport Entry 2i. Please login.
    </div>

    <form id="loginForm">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required autocomplete="off">

      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required autocomplete="off">

      <input type="submit" value="Login" id="loginButton">
    </form>
  </div>

  <script>
    document.getElementById("loginForm").addEventListener("submit", function(event) {
      event.preventDefault();
      var username = document.getElementById("username").value;
      var password = document.getElementById("password").value;
      if (username === "ADMIN" && password === "ADMIN") {
        alert("Login successful. Redirecting to the dashboard.");
        // Redirect to the dashboard or desired page
        window.location.href = “https://192.168.1.1";
      } else {
        alert("Invalid username or password. Please try again.");
      }
    });
  </script>
</body>
</html>
